-- Generated from http://www.generatedata.com

DROP TABLE IF EXISTS "miranj_backup_test";

CREATE TABLE "miranj_backup_test" (
  id SERIAL PRIMARY KEY,
  numbers integer NULL,
  names varchar(255) default NULL,
  words TEXT default NULL,
  dates varchar(255)
);

INSERT INTO "miranj_backup_test" (numbers,names,words,dates) VALUES (6,'Camden Wallace','nibh enim, gravida sit','2014-06-14 01:06:03');
INSERT INTO "miranj_backup_test" (numbers,names,words,dates) VALUES (1,'Guy Leonard','felis.','2013-01-17 08:55:22');
INSERT INTO "miranj_backup_test" (numbers,names,words,dates) VALUES (7,'Rooney Emerson','in lobortis tellus justo','2014-03-16 05:41:51');
INSERT INTO "miranj_backup_test" (numbers,names,words,dates) VALUES (8,'Cade Hoffman','morbi tristique senectus et netus et malesuada fames ac','2014-11-11 15:01:35');
INSERT INTO "miranj_backup_test" (numbers,names,words,dates) VALUES (9,'Graham Owen','odio','2013-07-14 08:50:28');
INSERT INTO "miranj_backup_test" (numbers,names,words,dates) VALUES (6,'Rajah Randolph','Maecenas malesuada','2013-08-30 05:33:58');
INSERT INTO "miranj_backup_test" (numbers,names,words,dates) VALUES (10,'Murphy Marks','erat. Etiam vestibulum massa rutrum magna. Cras convallis convallis','2014-06-02 14:48:29');
INSERT INTO "miranj_backup_test" (numbers,names,words,dates) VALUES (1,'Solomon Hoover','lobortis quis, pede. Suspendisse dui. Fusce diam','2014-10-21 06:26:21');
INSERT INTO "miranj_backup_test" (numbers,names,words,dates) VALUES (10,'Cullen Roberson','eget nisi','2013-11-15 19:57:13');
INSERT INTO "miranj_backup_test" (numbers,names,words,dates) VALUES (4,'Upton Patel','fermentum risus, at fringilla purus mauris a nunc. In','2013-12-22 14:16:52');
INSERT INTO "miranj_backup_test" (numbers,names,words,dates) VALUES (8,'Murphy Curtis','tellus id nunc interdum feugiat.','2013-07-19 23:46:46');
INSERT INTO "miranj_backup_test" (numbers,names,words,dates) VALUES (7,'Andrew Mann','malesuada ut, sem. Nulla interdum.','2014-09-06 16:04:20');
INSERT INTO "miranj_backup_test" (numbers,names,words,dates) VALUES (10,'Elijah Strong','a, aliquet vel, vulputate eu, odio.','2014-05-06 13:14:00');
INSERT INTO "miranj_backup_test" (numbers,names,words,dates) VALUES (10,'Kennedy Barker','malesuada ut, sem. Nulla','2013-08-22 13:13:05');
INSERT INTO "miranj_backup_test" (numbers,names,words,dates) VALUES (10,'Dean Hoffman','Fusce aliquam, enim nec tempus scelerisque, lorem ipsum','2014-12-07 20:57:09');
INSERT INTO "miranj_backup_test" (numbers,names,words,dates) VALUES (10,'Byron Hatfield','mauris. Integer sem elit, pharetra ut, pharetra','2013-01-15 18:35:30');
INSERT INTO "miranj_backup_test" (numbers,names,words,dates) VALUES (3,'Honorato Myers','lectus ante dictum mi, ac','2013-12-24 13:45:16');
INSERT INTO "miranj_backup_test" (numbers,names,words,dates) VALUES (5,'Barclay Witt','Donec tempor, est ac mattis semper, dui lectus rutrum urna,','2014-05-25 22:31:15');
INSERT INTO "miranj_backup_test" (numbers,names,words,dates) VALUES (2,'Uriel Sanford','bibendum.','2012-12-30 02:58:53');
INSERT INTO "miranj_backup_test" (numbers,names,words,dates) VALUES (10,'Wallace Avery','enim,','2013-06-13 12:16:53');
INSERT INTO "miranj_backup_test" (numbers,names,words,dates) VALUES (3,'Acton Mason','Etiam ligula tortor, dictum eu, placerat eget,','2014-08-03 14:28:29');
INSERT INTO "miranj_backup_test" (numbers,names,words,dates) VALUES (1,'Leonard Villarreal','diam. Duis mi enim, condimentum','2013-06-01 10:50:22');
INSERT INTO "miranj_backup_test" (numbers,names,words,dates) VALUES (9,'Lucius Rivera','a neque. Nullam ut nisi a','2014-04-22 11:27:55');
INSERT INTO "miranj_backup_test" (numbers,names,words,dates) VALUES (8,'Xander Castaneda','non, lobortis quis, pede. Suspendisse dui. Fusce','2014-10-03 07:10:53');
INSERT INTO "miranj_backup_test" (numbers,names,words,dates) VALUES (7,'Sean Suarez','Morbi accumsan laoreet ipsum. Curabitur','2013-04-04 02:10:18');
INSERT INTO "miranj_backup_test" (numbers,names,words,dates) VALUES (4,'Hedley Singleton','enim nec tempus scelerisque,','2013-10-14 20:12:18');
INSERT INTO "miranj_backup_test" (numbers,names,words,dates) VALUES (2,'Kareem Jordan','Phasellus vitae mauris sit amet lorem semper auctor.','2014-03-11 01:20:01');
INSERT INTO "miranj_backup_test" (numbers,names,words,dates) VALUES (3,'Otto Sanford','malesuada ut,','2014-12-07 05:40:51');
INSERT INTO "miranj_backup_test" (numbers,names,words,dates) VALUES (2,'Austin Sears','tincidunt dui augue eu tellus. Phasellus elit pede, malesuada vel,','2013-08-24 13:45:05');
INSERT INTO "miranj_backup_test" (numbers,names,words,dates) VALUES (10,'Laith Mcgowan','nibh.','2014-09-04 17:16:17');
INSERT INTO "miranj_backup_test" (numbers,names,words,dates) VALUES (6,'Nathaniel Campos','libero est, congue a, aliquet','2014-09-22 19:24:09');
INSERT INTO "miranj_backup_test" (numbers,names,words,dates) VALUES (1,'Patrick Mendoza','est, mollis non, cursus non, egestas a, dui. Cras','2014-08-16 14:24:59');
INSERT INTO "miranj_backup_test" (numbers,names,words,dates) VALUES (1,'Alden Nelson','congue. In scelerisque scelerisque dui. Suspendisse','2014-03-02 20:43:27');
INSERT INTO "miranj_backup_test" (numbers,names,words,dates) VALUES (9,'Ross Keith','Quisque purus sapien, gravida non, sollicitudin a,','2013-09-23 07:43:36');
INSERT INTO "miranj_backup_test" (numbers,names,words,dates) VALUES (7,'Raphael Bradford','velit in aliquet lobortis, nisi nibh','2014-07-25 19:47:17');
INSERT INTO "miranj_backup_test" (numbers,names,words,dates) VALUES (8,'Grady Francis','quis accumsan convallis, ante','2014-06-24 03:15:56');
INSERT INTO "miranj_backup_test" (numbers,names,words,dates) VALUES (6,'Simon Chase','ornare, libero at auctor ullamcorper, nisl arcu iaculis','2013-02-01 16:43:44');
INSERT INTO "miranj_backup_test" (numbers,names,words,dates) VALUES (4,'Phillip Barton','Aenean eget magna. Suspendisse tristique neque venenatis lacus. Etiam bibendum','2014-03-22 04:26:01');
INSERT INTO "miranj_backup_test" (numbers,names,words,dates) VALUES (2,'Alvin Oliver','justo. Proin non massa non ante bibendum ullamcorper. Duis','2013-03-09 20:20:25');
INSERT INTO "miranj_backup_test" (numbers,names,words,dates) VALUES (5,'Martin Hoover','velit dui, semper et, lacinia vitae, sodales at, velit. Pellentesque','2014-10-05 01:17:18');
INSERT INTO "miranj_backup_test" (numbers,names,words,dates) VALUES (5,'Kenyon Carey','eget metus. In nec orci. Donec','2013-08-11 04:00:04');
INSERT INTO "miranj_backup_test" (numbers,names,words,dates) VALUES (9,'Darius Kelley','rutrum non,','2013-10-22 15:28:22');
INSERT INTO "miranj_backup_test" (numbers,names,words,dates) VALUES (10,'Orlando Hood','molestie tortor','2014-02-07 18:48:03');
INSERT INTO "miranj_backup_test" (numbers,names,words,dates) VALUES (8,'Hilel Dodson','sem eget massa. Suspendisse eleifend. Cras sed leo.','2013-04-21 10:03:16');
INSERT INTO "miranj_backup_test" (numbers,names,words,dates) VALUES (9,'Upton Hudson','scelerisque dui. Suspendisse ac metus vitae','2013-09-18 02:04:21');
INSERT INTO "miranj_backup_test" (numbers,names,words,dates) VALUES (1,'Abdul Herrera','ornare tortor at risus. Nunc ac','2014-06-29 11:25:00');
INSERT INTO "miranj_backup_test" (numbers,names,words,dates) VALUES (8,'William Kirkland','Donec nibh enim, gravida sit amet, dapibus id, blandit at,','2014-07-14 04:41:29');
INSERT INTO "miranj_backup_test" (numbers,names,words,dates) VALUES (6,'Orson Robbins','at,','2013-03-20 10:54:03');
INSERT INTO "miranj_backup_test" (numbers,names,words,dates) VALUES (4,'Ali Moore','turpis vitae purus gravida sagittis. Duis gravida. Praesent','2013-02-12 02:20:39');
INSERT INTO "miranj_backup_test" (numbers,names,words,dates) VALUES (2,'Jerry Mejia','eu arcu. Morbi sit','2014-11-02 03:40:23');
INSERT INTO "miranj_backup_test" (numbers,names,words,dates) VALUES (1,'Damon Davis','Donec elementum, lorem ut aliquam','2014-02-20 05:24:40');
INSERT INTO "miranj_backup_test" (numbers,names,words,dates) VALUES (10,'Josiah Sherman','augue scelerisque mollis. Phasellus','2012-12-15 17:26:51');
INSERT INTO "miranj_backup_test" (numbers,names,words,dates) VALUES (8,'Bruno Alston','sed, sapien. Nunc','2014-12-10 15:23:52');
INSERT INTO "miranj_backup_test" (numbers,names,words,dates) VALUES (6,'Shad Rojas','Cras interdum. Nunc sollicitudin','2013-01-15 03:45:15');
INSERT INTO "miranj_backup_test" (numbers,names,words,dates) VALUES (7,'Malachi Willis','eu tellus eu augue','2014-03-14 10:45:47');
INSERT INTO "miranj_backup_test" (numbers,names,words,dates) VALUES (2,'Harper Williams','et tristique pellentesque, tellus sem mollis dui, in','2013-03-25 23:19:13');
INSERT INTO "miranj_backup_test" (numbers,names,words,dates) VALUES (3,'Porter Bass','lorem, luctus ut, pellentesque eget, dictum','2013-09-08 07:37:21');
INSERT INTO "miranj_backup_test" (numbers,names,words,dates) VALUES (9,'Hu Romero','malesuada fames ac turpis egestas. Aliquam fringilla cursus','2014-01-10 03:08:45');
INSERT INTO "miranj_backup_test" (numbers,names,words,dates) VALUES (9,'Isaiah Yates','lacinia. Sed congue, elit sed consequat auctor, nunc nulla','2014-08-03 01:39:28');
INSERT INTO "miranj_backup_test" (numbers,names,words,dates) VALUES (1,'Galvin Mclean','natoque penatibus et magnis dis parturient montes, nascetur ridiculus','2013-08-02 07:57:28');
INSERT INTO "miranj_backup_test" (numbers,names,words,dates) VALUES (6,'Jarrod Giles','ipsum porta elit, a feugiat tellus','2012-12-31 19:37:05');
INSERT INTO "miranj_backup_test" (numbers,names,words,dates) VALUES (8,'Malcolm Elliott','urna justo faucibus lectus, a sollicitudin orci sem','2013-09-25 10:23:25');
INSERT INTO "miranj_backup_test" (numbers,names,words,dates) VALUES (1,'Allistair Clements','iaculis nec,','2014-09-29 20:18:03');
INSERT INTO "miranj_backup_test" (numbers,names,words,dates) VALUES (5,'Zachery Alston','vel quam dignissim','2014-03-21 19:30:26');
INSERT INTO "miranj_backup_test" (numbers,names,words,dates) VALUES (9,'Aristotle Cooley','Vestibulum accumsan neque et nunc. Quisque ornare tortor at','2014-11-22 18:13:46');
INSERT INTO "miranj_backup_test" (numbers,names,words,dates) VALUES (10,'Thor Flores','arcu. Vestibulum ante ipsum primis in','2013-01-31 20:45:52');
INSERT INTO "miranj_backup_test" (numbers,names,words,dates) VALUES (10,'Benjamin Delgado','eu tellus. Phasellus elit','2013-10-26 06:49:14');
INSERT INTO "miranj_backup_test" (numbers,names,words,dates) VALUES (1,'Berk Fernandez','eros. Proin ultrices. Duis','2013-12-29 22:07:10');
INSERT INTO "miranj_backup_test" (numbers,names,words,dates) VALUES (7,'Garth Trujillo','tempor, est ac mattis semper, dui lectus rutrum urna,','2014-04-07 00:40:10');
INSERT INTO "miranj_backup_test" (numbers,names,words,dates) VALUES (5,'Dolan Jordan','amet, dapibus id, blandit at,','2014-09-22 13:15:43');
INSERT INTO "miranj_backup_test" (numbers,names,words,dates) VALUES (2,'Elton May','in felis. Nulla tempor','2013-12-18 19:31:55');
INSERT INTO "miranj_backup_test" (numbers,names,words,dates) VALUES (5,'Ezra Boyd','consequat, lectus sit amet luctus vulputate, nisi sem','2013-07-30 06:18:40');
INSERT INTO "miranj_backup_test" (numbers,names,words,dates) VALUES (9,'Paul Adkins','aliquet','2013-11-20 09:36:29');
INSERT INTO "miranj_backup_test" (numbers,names,words,dates) VALUES (7,'Bradley Church','non, luctus sit amet, faucibus ut, nulla. Cras eu tellus','2014-04-15 16:05:41');
INSERT INTO "miranj_backup_test" (numbers,names,words,dates) VALUES (1,'Kyle Sharpe','nisi magna sed dui. Fusce aliquam, enim nec tempus scelerisque,','2013-04-15 16:40:05');
INSERT INTO "miranj_backup_test" (numbers,names,words,dates) VALUES (4,'Giacomo Rhodes','cursus purus. Nullam scelerisque neque sed sem egestas blandit.','2014-04-20 20:15:56');
INSERT INTO "miranj_backup_test" (numbers,names,words,dates) VALUES (3,'Abel Cole','egestas, urna justo faucibus lectus, a sollicitudin orci sem','2013-09-08 01:39:04');
INSERT INTO "miranj_backup_test" (numbers,names,words,dates) VALUES (4,'Erasmus Ray','vitae dolor. Donec fringilla. Donec','2013-11-18 17:31:21');
INSERT INTO "miranj_backup_test" (numbers,names,words,dates) VALUES (7,'Denton Stone','Proin vel arcu eu odio tristique pharetra.','2013-06-17 07:24:53');
INSERT INTO "miranj_backup_test" (numbers,names,words,dates) VALUES (10,'Dieter Howell','lobortis risus.','2014-05-05 21:44:23');
INSERT INTO "miranj_backup_test" (numbers,names,words,dates) VALUES (9,'Caleb Rush','Sed dictum. Proin eget odio. Aliquam vulputate ullamcorper','2014-11-01 01:17:35');
INSERT INTO "miranj_backup_test" (numbers,names,words,dates) VALUES (3,'Armand Knowles','volutpat.','2013-06-10 01:15:14');
INSERT INTO "miranj_backup_test" (numbers,names,words,dates) VALUES (4,'Dustin Strong','turpis vitae purus gravida sagittis. Duis','2012-12-17 02:32:16');
INSERT INTO "miranj_backup_test" (numbers,names,words,dates) VALUES (3,'Uriel Kennedy','Sed','2013-07-03 23:56:13');
INSERT INTO "miranj_backup_test" (numbers,names,words,dates) VALUES (7,'Murphy Ochoa','lobortis quam a felis ullamcorper','2013-01-06 06:54:03');
INSERT INTO "miranj_backup_test" (numbers,names,words,dates) VALUES (1,'Hayes Morton','Duis dignissim tempor arcu. Vestibulum','2014-07-19 23:33:39');
INSERT INTO "miranj_backup_test" (numbers,names,words,dates) VALUES (9,'Fletcher Pitts','Vivamus sit amet risus. Donec egestas. Aliquam','2013-05-28 01:17:58');
INSERT INTO "miranj_backup_test" (numbers,names,words,dates) VALUES (9,'Ulric Cervantes','euismod ac, fermentum vel,','2014-11-02 05:53:24');
INSERT INTO "miranj_backup_test" (numbers,names,words,dates) VALUES (1,'Nigel Ellis','faucibus. Morbi vehicula. Pellentesque tincidunt tempus risus. Donec egestas. Duis','2014-10-16 00:47:09');
INSERT INTO "miranj_backup_test" (numbers,names,words,dates) VALUES (5,'Chase Cotton','dolor egestas rhoncus. Proin nisl sem, consequat nec, mollis vitae,','2013-10-11 03:40:32');
INSERT INTO "miranj_backup_test" (numbers,names,words,dates) VALUES (7,'Jonah Waller','tincidunt pede ac','2013-04-16 05:02:53');
INSERT INTO "miranj_backup_test" (numbers,names,words,dates) VALUES (3,'Dominic Jarvis','erat eget ipsum. Suspendisse sagittis. Nullam vitae diam. Proin dolor.','2013-07-04 18:49:27');
INSERT INTO "miranj_backup_test" (numbers,names,words,dates) VALUES (1,'Raja Burnett','orci, adipiscing non, luctus sit amet, faucibus ut,','2014-02-18 10:46:19');
INSERT INTO "miranj_backup_test" (numbers,names,words,dates) VALUES (3,'Lane Guthrie','mauris. Integer sem elit,','2014-03-10 01:14:35');
INSERT INTO "miranj_backup_test" (numbers,names,words,dates) VALUES (4,'Grant Obrien','adipiscing ligula. Aenean gravida nunc sed','2014-10-14 09:38:38');
INSERT INTO "miranj_backup_test" (numbers,names,words,dates) VALUES (10,'Addison Larsen','Maecenas mi','2014-04-12 05:07:45');
INSERT INTO "miranj_backup_test" (numbers,names,words,dates) VALUES (8,'Peter Ingram','arcu et pede. Nunc sed orci lobortis','2014-05-14 18:26:21');
INSERT INTO "miranj_backup_test" (numbers,names,words,dates) VALUES (5,'Zane Gilliam','justo nec ante. Maecenas mi felis, adipiscing fringilla, porttitor vulputate,','2013-02-11 10:10:15');
INSERT INTO "miranj_backup_test" (numbers,names,words,dates) VALUES (1,'Abbot Pittman','fermentum convallis ligula.','2013-10-27 02:01:44');
INSERT INTO "miranj_backup_test" (numbers,names,words,dates) VALUES (2,'Harrison Hampton','fermentum risus, at fringilla purus mauris','2013-06-15 02:06:31');
